### ISSUE TITLE
Is memory (address space) fragmentation addressed?

### ISSUE THREAD

**Issue by complyue** [Avi-D-coder/sundial-gc-design#1]
Years ago, I witnessed a customer's WebSphere server OOM crash, due to the application my former employer deployed, asking for a 11MB buffer, while the JVM (IBM VM) still have overall 700+MB free on the heap, it can not find a contiguous region long enough to satisfy the allocation.

I was surprised as Java has its GC designed with possibly objects getting moved around, but apparently it did not do that in that very case.

I also heard GHC is currently using a moving GC, and finishing a non-moving GC toward 8.10 or the like. Seeing your design here reminds me this interesting aspect, I'd like to see your insights about the situation.

**Comment by Avi-D-coder** [comment]
This is a very aggressive copying GC, so fragmentation is not really an issue. With that being said large allocations, should usually go into the Rust heap with only a fat pointer in the GC heap. Even with moving GCs use of non moving primitives 

> I also heard GHC is currently using a moving GC, and finishing a non-moving GC toward 8.10 or the like. Seeing your design here reminds me this interesting aspect, I'd like to see your insights about the situation.

Non moving or compacting generations will eventually happen, but are likely not scope for the 12 week implementation. The nice thing about Sundial is, since generational promotion only done by dedicated GC threads, heuristics can be used to decide if a arena should be promoted, and holes filled in, vs moving all objects out. Where as the new Haskell GC just kicks in at the last generation.

**Comment by complyue** [comment]
Great to hear! Fragmentation not only can fail, but can badly affect overall performance for long running programs, Sundial seems promising.

I'm sure I can't understand quite the details, but I'm very curious how pauseless is achieved, I think there is a race condition for a GC thread to copy or move a block of mem at the same time an app thread is writing there halfway, how is that coordinated ?

**Comment by Avi-D-coder** [comment]
Nope no race conditions ;)
I worked on the design for 8 months. While I have not yet written a TLA+ model, I'm very confident I tracked down all the races.

> I think there is a race condition for a GC thread to copy or move a block of mem at the same time an app thread is writing there halfway, how is that coordinated?

Mutation is not allowed, if you need mutable `Gc<T>` you will have to use `Gc<Box<Mutex<WeakRoot<T>>>>` until first class mutation is added. 

The basic principle of Sundial is worker threads know when an arena is condemned. First class mutation in a condemned region triggers a move prior to mutation, this is more expensive for both the GC and the works.
Reads and writes trigger a check to see if the pointer is in a known condemned region, if it is an acquire read is used to determine the new location of the object or need to move. The actual implementation will unconditionally do an aquire check for a move, rather then first checking if a region is known (by the worker) to be condemned. If we pad mutable objects with a pointer this will usually be faster on X86, though it may not be on more weakly ordered ISAs (Arm).

 This is okay since the GC is optimized for

**Comment by complyue** [comment]
Yeah, I'm enlightened, I couldn't help thinking in C++/Java etc. those old envs where mutable objects are the only sane data structures, even after I have benefited a lot from STM with immutable data as majority.

Yes, explicit mutability management is the cure. Then do you think STM and GC have something to integrate with each other, or they'd better stay orthogonal?

My impression so far is that STM gives business programmers relief from thinking too much about **how** concurrency should be resolved, but **what** is the right thing to do, leaving the computer to (re)try the **right thing** with best efforts. But honestly I haven't put that intensive usage into daily operations of my team, not quite sure how much non-progressive situation we'll suffer then.

**Comment by Avi-D-coder** [comment]
There are two STM libraries in Rust, I'm going to look at integrating one of them, once the GC is done.

**Comment by complyue** [comment]
Is there any chance for Sundial to be implemented for GHC? I'm not sure GHC can easily run with alternative GC, then have you looked at the possibility?

**Comment by Avi-D-coder** [comment]
Not directly. In the very long run it could possibly be used by GRIN. And GRIN has a GHC front end.
